# Generated by Django 3.0.8 on 2020-10-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='subscribe',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
